apiVersion: v1
kind: Pod
metadata:
  name: postgresql-backup-s3-restore
spec:
  containers:
    - name: postgresql-backup-s3-restore
      image: sverrirab/postgresql-backup-s3
      command:
      - sleep
      - infinity
      env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-backup-s3
              key: pgpassword
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: postgresql-backup-s3
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: postgresql-backup-s3
              key: aws_secret_access_key
      envFrom:
        - configMapRef:
            # You can override the values above in the config map
            name: postgresql-backup-s3-config
      volumeMounts:
        - mountPath: "/opt/restore"
          name: restore-vol
  volumes:
    - name: restore-vol
      hostPath:
        path: "/opt/restore"
        type: Directory
