apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup-s3-daily
spec:
  concurrencyPolicy: Forbid
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 14
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: postgresql-backup-s3
              image: sverrirab/postgresql-backup-s3
              env:
                - name: DEST_S3_FOLDER
                  value: daily
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-backup-s3
                      key: pgpassword
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-backup-s3
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-backup-s3
                      key: aws_secret_access_key
              envFrom:
                - configMapRef:
                    # You can override the values above in the config map
                    # Note: there are required parameters in the map you need to edit
                    name: postgresql-backup-s3-config
